//! # GTFS Schedule Entities
//!
//! One struct per GTFS Schedule file and one enum per enumerated
//! field, covering the complete specification. Field names follow the
//! spec verbatim. Required fields are plain values, optional fields
//! are `Option`s, and enumerated fields with a spec-defined default
//! are plain enums implementing [`Default`].
//!
//! Entity structs are `#[non_exhaustive]`: construct them with their
//! `new` constructors (and `with_*` builders), then set any remaining
//! optional fields directly - all fields are public.
//!
//! Reference: <https://gtfs.org/documentation/schedule/reference/>

/// Generates a GTFS numeric enum with `from_code`/`code` conversions.
macro_rules! gtfs_enum {
    (
        $(#[$meta:meta])*
        $name:ident {
            $( $(#[$vmeta:meta])* $variant:ident = $code:literal ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum $name {
            $( $(#[$vmeta])* $variant, )+
        }

        impl $name {
            /// Parses the numeric code used in GTFS files.
            ///
            /// # Examples
            ///
            /// Shown with [`LocationType`](crate::LocationType); every
            /// enum generated by the crate converts the same way.
            ///
            /// ```
            /// use gtfs_rs::LocationType;
            ///
            /// assert_eq!(
            ///     LocationType::from_code(1),
            ///     Some(LocationType::Station),
            /// );
            /// assert_eq!(LocationType::from_code(99), None);
            /// ```
            pub fn from_code(code: i32) -> Option<Self> {
                match code {
                    $( $code => Some(Self::$variant), )+
                    _ => None,
                }
            }

            /// Returns the numeric code used in GTFS files.
            ///
            /// # Examples
            ///
            /// Shown with [`LocationType`](crate::LocationType); every
            /// enum generated by the crate converts the same way.
            ///
            /// ```
            /// use gtfs_rs::LocationType;
            ///
            /// assert_eq!(LocationType::Station.code(), 1);
            /// ```
            pub fn code(self) -> i32 {
                match self {
                    $( Self::$variant => $code, )+
                }
            }
        }
    };
}

mod agency;
mod areas;
mod attributions;
mod booking;
mod calendar;
mod fares;
mod feed_info;
mod frequencies;
mod levels;
mod locations;
mod networks;
mod pathways;
mod routes;
mod shapes;
mod stop_times;
mod stops;
mod transfers;
mod translations;
mod trips;

pub use agency::{Agency, CemvSupport};
pub use areas::{Area, StopArea};
pub use attributions::Attribution;
pub use booking::{BookingRule, BookingType};
pub use calendar::{Calendar, CalendarDate, ExceptionType};
pub use fares::{
    DurationLimitType, FareAttributeV1, FareLegJoinRule, FareLegRule, FareMedia, FareMediaType,
    FareProduct, FareRuleV1, FareTransferRule, FareTransferType, FareTransfers, PaymentMethod,
    RiderCategory, Timeframe,
};
pub use feed_info::FeedInfo;
pub use frequencies::{ExactTimes, Frequency};
pub use levels::Level;
pub use locations::{Location, LocationGeometry, LocationGroup, LocationGroupStop};
pub use networks::{Network, RouteNetwork};
pub use pathways::{Pathway, PathwayMode};
pub use routes::{ContinuousPickupDropOff, Route, RouteType};
pub use shapes::ShapePoint;
pub use stop_times::{PickupDropOffType, StopTime, Timepoint};
pub use stops::{LocationType, Stop, StopAccess, WheelchairBoarding};
pub use transfers::{Transfer, TransferType};
pub use translations::{TableName, Translation};
pub use trips::{BikesAllowed, CarsAllowed, Direction, Trip, WheelchairAccessible};
